utb_eshop_patek/utb_eshop_patek/Areas/Admin/Controllers/Common/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace utb_eshop_patek.Areas.Admin.Controllers.Common
{
    [Authorize(Roles = "Manager, Admin"), Area("Admin")]
    public class AdminController : Controller
    {
    }
}

utb_eshop_patek/utb_eshop_patek/Areas/Admin/Controllers/ProductsController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using utb_eshop_patek.Application.Admin.ApplicationServices.Products;
using utb_eshop_patek.Application.Admin.ViewModels.Products;
using utb_eshop_patek.Areas.Admin.Controllers.Common;

namespace utb_eshop_patek.Areas.Admin.Controllers
{
    public class ProductsController : AdminController
    {
        private readonly IProductApplicationService _productApplicationService;

        public ProductsController(IProductApplicationService productApplicationService)
        {
            _productApplicationService = productApplicationService;
        }

        public IActionResult Index()
        {
            var vm = _productApplicationService.GetIndexViewModel();
            return View(vm);
        }

        public IActionResult Edit(int id)
        {
            var product = _productApplicationService.GetProductViewModel(id);
            return View(product);
        }

        [HttpPost]
        public IActionResult Edit(ProductViewModel model)
        {
            var product = _productApplicationService.Update(model);
            return Json(product);
        }

        public IActionResult Insert()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Insert(ProductViewModel model)
        {
            var product = _productApplicationService.Insert(model);
            return Json(product);
        }

        public IActionResult Delete(ProductViewModel model)
        {
            _productApplicationService.Delete(model);
            return RedirectToAction(nameof(Index));
        }
    }
}

utb_eshop_patek/utb_eshop_patek/Areas/Admin/Controllers/SecurityController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using utb_eshop_patek.Application.Admin.ApplicationServices.Security;
using utb_eshop_patek.Application.Admin.ViewModels.Security;
using utb_eshop_patek.Areas.Admin.Controllers.Common;

namespace utb_eshop_patek.Areas.Admin.Controllers
{
    [AllowAnonymous]
    public class SecurityController : AdminController
    {
        private readonly ISecurityApplicationService _securityApplicationService;

        public SecurityController(ISecurityApplicationService securityApplicationService)
        {
            _securityApplicationService = securityApplicationService;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel viewModel)
        {
            await _securityApplicationService.Login(viewModel);
            return RedirectToAction("Index", "Products", new { area = "Admin" });
        }

        public async Task<IActionResult> Logout()
        {
            await _securityApplicationService.Logout();
            return RedirectToAction(nameof(Login));
        }
    }
}

utb_eshop_patek/utb_eshop_patek/Areas/Client/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using utb_eshop_patek.Application.Client.ApplicationServices.Carts;
using utb_eshop_patek.Domain.Constants;

namespace utb_eshop_patek.Areas.Client.Controllers
{
    [Area("Client")]
    public class CartsController : Controller
    {
        private readonly ICartApplicationService _cartApplicationService;

        public CartsController(ICartApplicationService cartApplicationService)
        {
            _cartApplicationService = cartApplicationService;
        }

        public IActionResult Index()
        {
            var vm = _cartApplicationService.GetIndexViewModel(GetTrackingCode());
            return View(vm);
        }

        [HttpPost]
        public JsonResult AddToCart(int id, int amount)
        {
            var cartItem = _cartApplicationService.AddToCart(id, amount, GetTrackingCode());
            return Json(cartItem);
        }

        [HttpPost]
        public JsonResult RemoveFromCart(int id)
        {
            _cartApplicationService.RemoveFromCart(id, GetTrackingCode());
            return Json("success");
        }

        private string GetTrackingCode()
        {
            var utc = Request.Cookies[Cookies.UserTrackingCode];
            if (utc != null)
                return utc;

            var guid = Guid.NewGuid().ToString();
            var options = new CookieOptions();
            options.Expires = DateTime.Now.AddYears(1);

            Response.Cookies.Append(Cookies.UserTrackingCode, guid, options);
            return guid;
        }
    }
}

utb_eshop_patek/utb_eshop_patek/Areas/Client/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using utb_eshop_patek.Application.Admin.ApplicationServices.Products;

namespace utb_eshop_patek.Areas.Client.Controllers
{
    [Area("Client")]
    public class ProductsController : Controller
    {
        private readonly IProductApplicationService _productApplicationService;

        public ProductsController(IProductApplicationService productApplicationService)
        {
            _productApplicationService = productApplicationService;
        }

        public IActionResult Index()
        {
            var vm = _productApplicationService.GetIndexViewModel();
            return View(vm);
        }
        public IActionResult Detail(int id)
        {
            var vm = _productApplicationService.GetProductViewModel(id);
            return View(vm);
        }
    }
}

utb_eshop_patek/utb_eshop_patek/Areas/Admin/Views/Products/Edit.cshtml
@model ProductViewModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>ProductViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <label>@Model.ID</label>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageURL" class="control-label"></label>
                <input asp-for="ImageURL" class="form-control" />
                <span asp-validation-for="ImageURL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

utb_eshop_patek/utb_eshop_patek/Areas/Admin/Views/Products/Index.cshtml
@model IndexViewModel

@{
    ViewData["Title"] = "Index";
}

<h2>Produkty</h2>

<div class="col-xs-1 col-lg-offset-11">
    <button type="button" class="btn btn-default" id="btn-insert">
        <i class="glyphicon-plus"></i>
    </button>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                Name
            </th>
            <th>
                Price
            </th>
            <th>
                Image
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Products)
        {
            <tr>
                <td class="id">
                    @Html.DisplayFor(modelItem => item.ID)
                </td>
                <td class="name">
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td class="price">
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td class="image">
                    <img class="image-thumbnail" src="@item.ImageURL" alt="@item.Name" />
                </td>
                <td class="actions">
                    <button type="button" class="btn btn-success btn-edit">Editovat</button>
                    <button data-id="@item.ID" type="button" class="btn btn-danger btn-delete">Smazat</button>
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts{
    <script>
        $(document).ready(() => {
            $('#btn-insert').click(createRow);
            $(document).on('click', '.btn-discard', discard);
            $(document).on('click', '.btn-save', insert);
            $(document).on('click', '.btn-edit', edit);
            $(document).on('click', '.btn-update', update);
            $(document).on('click', '.btn-delete', deleteProduct);
        });

        function deleteProduct() {
            let id = $(this).data('id');
            $.ajax({
                url: '@Url.Action("Delete")',
                data: { id: id }
            });

            $(this).closest('tr').remove();
        }

        function edit() {
            const row = $(this).closest('tr');
            let id = row.find('.id').text(),
                name = row.find('.name').text(),
                price = row.find('.price').text(),
                imageUrl = row.find('.image img').attr('src');

            row.find('.id').html('<input name="ID" type="number" class="form-control" value="' + parseInt(id) + '" readonly />');
            row.find('.name').html('<input name="Name" type="text" class="form-control" value="' + name.trim() + '" />');
            row.find('.price').html('<input name="Price" type="number" class="form-control" value="' + parseFloat(price) + '" />');
            row.find('.image').html('<input name="Image" type="file" class="form-control" />'
                                    + '<input name="ImageURL" type="hidden" value="' + imageUrl + '">');
            row.find('.actions').html('<button type="button" class="btn btn-success btn-update">Uložit</button>');
        }

        function sendData(actionUrl, context) {
            const row = $(context).closest('tr');
            const inputs = row.find('input');
            const form = document.createElement('form');
            inputs.map((i, input) => form.append(input.cloneNode()));
            const formData = new FormData(form);

            $.ajax({
                method: 'POST',
                url: actionUrl,
                data: formData,
                processData: false,
                contentType: false,
                success: function (data) {
                    row.find('.id').text(data.id);
                    row.find('.name').html(data.name);
                    row.find('.price').html(data.price);
                    row.find('.image').html(createImage(data.imageURL));
                    row.find('.actions').html(
                        '<button type="button" class="btn btn-success btn-edit">Editovat</button>'
                        + '<button data-id="' + data.id + '" type="button" class="btn btn-danger btn-delete">Smazat</button>'
                        )
                }
            });
        }

        function insert() {
            sendData('@Url.Action("Insert")', this);
        }

        function update() {
            sendData('@Url.Action("Edit")', this);
        }

        function createImage(url) {
            const img = document.createElement('img');
            img.src = url;
            img.classList.add('image-thumbnail');
            return img;
        }

        function discard() {
            const row = $(this).closest('tr');
            row.remove();
        }

        function createRow() {
            const table = $('table tbody');
            table.prepend(
                '<tr>'
                    + '<td class="id"></td>'
                    + '<td class="name">'
                        + '<input type="text" class="form-control" name="Name" />'
                    + '</td>'
                    + '<td class="price">'
                        + '<input type="number" class="form-control" name="Price" />'
                    + '</td>'
                    + '<td class="image">'
                        + '<input type="file" class="form-control" name="Image" />'
                    + '</td>'
                    + '<td class="actions">'
                        + '<button type="button" class="btn btn-primary btn-save">Uložit</button>'
                        + '<button type="button" class="btn btn-danger btn-discard">Zahodit</button>'
                    + '</td>'
                + '</tr>'
            );
        }
    </script>
}

utb_eshop_patek/utb_eshop_patek/Areas/Admin/Views/Products/Insert.cshtml
@model ProductViewModel

@{
    ViewData["Title"] = "Insert";
}

<h2>Insert</h2>

<h4>ProductViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Insert" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageURL" class="control-label"></label>
                <input asp-for="ImageURL" class="form-control" />
                <span asp-validation-for="ImageURL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

utb_eshop_patek/utb_eshop_patek/Areas/Admin/Views/Security/Login.cshtml
@model utb_eshop_patek.Application.Admin.ViewModels.Security.LoginViewModel

@{
    ViewData["Title"] = "Login";
}

<h2>Login</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Login" class="control-label"></label>
                <input asp-for="Login" class="form-control" />
                <span asp-validation-for="Login" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" type="password" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="RememberMe" /> @Html.DisplayNameFor(model => model.RememberMe)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

utb_eshop_patek/utb_eshop_patek/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - utb_eshop_patek</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Products" asp-action="Index" class="navbar-brand">utb_eshop_patek</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="Admin" asp-controller="Products" asp-action="Index">Admin</a></li>
                    <li><a asp-area="Admin" asp-controller="Security" asp-action="Logout">Logout</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - utb_eshop_patek</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

utb_eshop_patek/utb_eshop_patek/Areas/Client/Views/Carts/Index.cshtml
@model utb_eshop_patek.Application.Client.ViewModels.Carts.IndexViewModel

@{
    ViewData["Title"] = "Index";
}

<h2>Košík</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                Název
            </th>
            <th>
                Obrázek
            </th>
            <th>
                Množství
            </th>
            <th>
                Cena
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.CartItems) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>
                <img src="@item.ImageUrl" class="image-thumbnail" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
        </tr>
}
    </tbody>
</table>

<h3 class="col-lg-offset-10">
    Celkem: € @Model.Total
</h3>

utb_eshop_patek/utb_eshop_patek/Areas/Client/Views/Products/Detail.cshtml
@model utb_eshop_patek.Application.Admin.ViewModels.Products.ProductViewModel

@{
    ViewData["Title"] = "Detail";
}

<h2>Detail</h2>

<div>
    <h4>@Model.Name</h4>
    <hr />
    <div class="row">
        <div class="col-md-5">
            <img src="@Model.ImageURL" alt="@Model.Name" style="max-height:200px;" />
        </div>
        <div class="col-md-3">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Price)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Price)
                </dd>
            </dl>
        </div>
        <div class="col-md-2">
            <input class="form-control" type="number" value="1" />
            <button id="add-to-cart" data-id="@Model.ID" class="btn btn-primary">Přidat do košíku</button>

            <div class="alert alert-success" id="success-alert" style="display:none;">
                <button type="button" class="close" data-dismiss="alert">x</button>
                <strong>Added!</strong>
            </div>
        </div>
    </div>
</div>



@section scripts{
    <script>
    $(document).ready(() => {
        $('#add-to-cart').click(addToCart);
    });

    function addToCart() {
        var id = $(this).data('id');
        var amount = $(this).closest('div').find('input').val();

        $.ajax({
            method: 'POST',
            url: '@Url.Action("AddToCart", "Carts")',
            data: {id: id, amount: amount},
            success: function () {
                $("#success-alert").fadeTo(2000, 500).slideUp(500, function(){
                    $("#success-alert").slideUp(500);
                });
            }
        })
    }
    </script>
}

utb_eshop_patek/utb_eshop_patek/Areas/Client/Views/Products/Index.cshtml
@model IndexViewModel

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<div class="row">
    @foreach (var product in Model.Products)
    {
        <div class="col-xs-4">
            <div class="thumbnail">
                <img class="product-image" src="@product.ImageURL" alt="@product.Name" />
                <div class="caption">
                    <h3>@product.Name</h3>
                    <a class="btn btn-primary" asp-action="Detail" asp-route-id="@product.ID">Detail</a>
                </div>
            </div>
        </div>
    }
</div>

utb_eshop_patek/utb_eshop_patek/Areas/Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - utb_eshop_patek</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Products" asp-action="Index" class="navbar-brand">utb_eshop_patek</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="Admin" asp-controller="Products" asp-action="Index">Admin</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a asp-controller="Carts" asp-action="Index">
                            <i class="glyphicon glyphicon-shopping-cart"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - utb_eshop_patek</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>